import type { Prize } from "../types";

export const DUMMY_PLAYERS: string[] = [
  "Phạm Duy Sơn",
  "Đoàn Quốc Tuấn",
  "Phùng Tuấn Anh",
  "Phạm Thành Sang",
  "Nguyễn Tuấn Anh",
  "Nguyễn Vương Tài Mẫn",
  "Nguyễn Mạnh Dũng",
  "Nguyễn Thế Huy",
  "Lê Đức Hiếu",
  "Nguyễn Thành Trung",
  "Đậu Anh Tuấn",
  "Nguyễn Việt Hải",
  "Lê Đức Minh",
  "Trần Huy Hoàng",
  "Nguyễn Văn Nam",
  "Nguyễn Văn Đạt",
  "Nguyễn Đức Toàn",
  "Nguyễn Thị Minh Nguyệt",
  "Phan Quỳnh Hương",
  "Trần Hữu Hà",
  "Trần Thị Bích Thảo",
  "Phạm Phương Anh",
  "Nguyễn Hải My",
  "Nguyễn Hồng Yến",
  "Chu Quang Thắng",
  "Phùng Thị Nhung",
  "Ngô Quốc Phú",
  "Dương Hải Đăng",
  "Vũ Việt Dũng",
  "Vũ Đăng Hùng",
  "Vương Quỳnh Mai",
  "Bùi Thanh Thương",
  "Phạm Thanh Tùng",
  "Nguyễn Thành Nam",
  "Đào Minh Ngọc",
  "Ngô Mạnh Duy",
  "Nguyễn Diễm Linh",
  "Nguyễn Minh Thịnh",
  "Trần Minh Đức",
  "Phạm Huy Hoàng",
  "Đỗ Trí Hải",
  "Nguyễn Ngọc Phúc",
  "Đỗ Thành Nam",
  "Chu Trọng Đoàn",
  "Vương Tuấn Anh",
  "Hoàng Thị Thùy Dương",
  "Hoàng Thái Phiên",
  "Mai Diệu Linh",
  "Lê Thị Bích Ngọc",
  "Hoàng Thị Huyền Trang",
  "Vũ Thị Bích Huệ",
  "Vũ Bích Châm",
  "Nguyễn Quốc Anh Minh",
  "Bùi Hải Anh",
  "Đặng Thị Yến",
  "Nguyễn Thị Vân Anh",
  "Trần Phương Khánh",
  "Trần Thị Hồng Nhung",
  "Trần Thị Thu Anh",
  "Bùi Thị Mai Ly",
  "Đỗ Quốc Bình",
  "Phạm Thị Hồng Nhung",
  "Lê Thanh Bình",
  "Vũ Anh Tuấn",
  "Tô Minh Thọ",
  "Phạm Anh Dũng",
  "Nguyễn Xuân Nam",
  "Đinh Tiến Trường",
  "Nguyễn Ngọc Tuấn",
  "Bùi Hải Dương",
];

export const DUMMY_PRIZES: Prize[] = [
  {
    name: "VÉ TIÊU CHUẨN",
    count: 4,
  },
  {
    name: "VÉ NÂNG CAO",
    count: 3,
  },
  {
    name: "VÉ HẠNG NHẤT",
    count: 2,
  },
  {
    name: "VÉ ĐỘC ĐẮC",
    count: 1,
  },
];
